clc;
clear all;
close all;
A = imread('?C:\venki\MOVIES\GSA.jpg');
subplot(2,3,1);
imshow(A);
title('Input-colour Image');
subplot(2,3,2);
B=imadjust(A,([.3 .7],[]);
imshow(B);
title('Contrast Enhanced Color image');
C = rgb2gray(A);
subplot(2,3,3);
imshow(C);
title('Input-Gray Scale Image');
subplot(2,3,4);
D=imadjust(C,[.3 .7],[]);
imshow(C);
title('Contrast Enhanced Gray Scale Image');