clc;
clear all;
close all;
X=imread('C:\venki\MOVIES\GSA.jpg');
subplot(2,3,1);
imshow(X);
title('Input Image');
X = rgb2gray(X);
subplot(2,3,2);
imshow(X);
title('Grey Scale Image');
B=255-X;
subplot(2,3,3);
imshow(B);
title('Image Negative');
D=double(X);
c=1;
S=c* log(1+D);
T= 255/(c* log(256));
Logtrans=uint8(T*S);
subplot(2,3,4);
imshow(Logtrans);
title('Log Transformation');
G=0.6;
S1=c*(D.^G);
T1=255/ (c*(255. ^G));
Powerlawtransf= uint8(T1*S1);
subplot(2,3,5);
imshow(Powerlawtransf);
title('Powerlaw Transformation');