clc;
close all;
clear all;
i = imread('C:\venki\MOVIES\GSA.jpg');
subplot(4,2,1);
imshow(i);
title('Original image');
A = rgb2gray(i);
subplot(4,2,2);
imshow(A);
title('Grey Scale Image');
le=im2double(i);
level=graythresh(le);
bw = im2bw(le,level);
subplot(4,2,3);
imshow(bw);
title('Image graythrsh');
levell=0.2*bw;
subplot(4,2,4);
imshow(levell);
title('0.2 Slice');
level2=0.4*bw;
subplot(4,2,5);
imshow(level2);
title('0.4 Slice');
level3=0.6*bw;
subplot(4,2,6);
imshow(level3);
title('0.6 Slice');
level4=0.8*bw;
subplot(4,2,7);
imshow(level4);
title('0.8 Slice');
wertyu