clc;
clear all;
close all;
A = imread('C:\Users\Muni Venkat\Pictures\duke.png');
subplot(1,4,1);
imshow(A);
title('colour Image');
B = rgb2gray(A);
subplot(1,4,2);
imshow(B);
title('Grey Scale Image');
C = im2bw (A);
subplot(1,4,3);
imshow(C);
title('Binary Image');
D = 255-B;
subplot(1,4,4);
title('Negative Image');
imshow(D);